#DEV environment

app:
  message: Este é o arquivo property para o ${spring.application.name} especifico para ambiente DEV

spring:
  datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1
  username: sa
  password: sa